// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (name, owner_id, theme)
VALUES ($1, $2, $3)
RETURNING id, name, owner_id, created_at, updated_at, theme, narrative_summary, dm_notes, status, summarized_through, party, character_creation_complete
`

type CreateCampaignParams struct {
	Name    string
	OwnerID uuid.UUID
	Theme   string
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign, arg.Name, arg.OwnerID, arg.Theme)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.NarrativeSummary,
		&i.DmNotes,
		&i.Status,
		&i.SummarizedThrough,
		&i.Party,
		&i.CharacterCreationComplete,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, owner_id, created_at, updated_at, theme, narrative_summary, dm_notes, status, summarized_through, party, character_creation_complete FROM campaigns
WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.NarrativeSummary,
		&i.DmNotes,
		&i.Status,
		&i.SummarizedThrough,
		&i.Party,
		&i.CharacterCreationComplete,
	)
	return i, err
}

const getCampaignsByOwner = `-- name: GetCampaignsByOwner :many
SELECT id, name, owner_id, created_at, updated_at, theme, narrative_summary, dm_notes, status, summarized_through, party, character_creation_complete FROM campaigns
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCampaignsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, getCampaignsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Theme,
			&i.NarrativeSummary,
			&i.DmNotes,
			&i.Status,
			&i.SummarizedThrough,
			&i.Party,
			&i.CharacterCreationComplete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCharacterCreationComplete = `-- name: SetCharacterCreationComplete :one
UPDATE campaigns
SET character_creation_complete = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, owner_id, created_at, updated_at, theme, narrative_summary, dm_notes, status, summarized_through, party, character_creation_complete
`

type SetCharacterCreationCompleteParams struct {
	ID                        uuid.UUID
	CharacterCreationComplete bool
}

func (q *Queries) SetCharacterCreationComplete(ctx context.Context, arg SetCharacterCreationCompleteParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, setCharacterCreationComplete, arg.ID, arg.CharacterCreationComplete)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.NarrativeSummary,
		&i.DmNotes,
		&i.Status,
		&i.SummarizedThrough,
		&i.Party,
		&i.CharacterCreationComplete,
	)
	return i, err
}

const updateCampaignDMNotes = `-- name: UpdateCampaignDMNotes :one
UPDATE campaigns
SET dm_notes = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, owner_id, created_at, updated_at, theme, narrative_summary, dm_notes, status, summarized_through, party, character_creation_complete
`

type UpdateCampaignDMNotesParams struct {
	ID      uuid.UUID
	DmNotes string
}

func (q *Queries) UpdateCampaignDMNotes(ctx context.Context, arg UpdateCampaignDMNotesParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaignDMNotes, arg.ID, arg.DmNotes)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.NarrativeSummary,
		&i.DmNotes,
		&i.Status,
		&i.SummarizedThrough,
		&i.Party,
		&i.CharacterCreationComplete,
	)
	return i, err
}

const updateCampaignParty = `-- name: UpdateCampaignParty :one
UPDATE campaigns
SET party = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, owner_id, created_at, updated_at, theme, narrative_summary, dm_notes, status, summarized_through, party, character_creation_complete
`

type UpdateCampaignPartyParams struct {
	ID    uuid.UUID
	Party json.RawMessage
}

func (q *Queries) UpdateCampaignParty(ctx context.Context, arg UpdateCampaignPartyParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaignParty, arg.ID, arg.Party)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.NarrativeSummary,
		&i.DmNotes,
		&i.Status,
		&i.SummarizedThrough,
		&i.Party,
		&i.CharacterCreationComplete,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, owner_id, created_at, updated_at, theme, narrative_summary, dm_notes, status, summarized_through, party, character_creation_complete
`

type UpdateCampaignStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.NarrativeSummary,
		&i.DmNotes,
		&i.Status,
		&i.SummarizedThrough,
		&i.Party,
		&i.CharacterCreationComplete,
	)
	return i, err
}

const updateCampaignTheme = `-- name: UpdateCampaignTheme :one
UPDATE campaigns
SET theme = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, owner_id, created_at, updated_at, theme, narrative_summary, dm_notes, status, summarized_through, party, character_creation_complete
`

type UpdateCampaignThemeParams struct {
	ID    uuid.UUID
	Theme string
}

func (q *Queries) UpdateCampaignTheme(ctx context.Context, arg UpdateCampaignThemeParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaignTheme, arg.ID, arg.Theme)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.NarrativeSummary,
		&i.DmNotes,
		&i.Status,
		&i.SummarizedThrough,
		&i.Party,
		&i.CharacterCreationComplete,
	)
	return i, err
}

const updateNarrativeSummary = `-- name: UpdateNarrativeSummary :one
UPDATE campaigns
SET narrative_summary = $2,
    summarized_through = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, owner_id, created_at, updated_at, theme, narrative_summary, dm_notes, status, summarized_through, party, character_creation_complete
`

type UpdateNarrativeSummaryParams struct {
	ID                uuid.UUID
	NarrativeSummary  string
	SummarizedThrough int32
}

func (q *Queries) UpdateNarrativeSummary(ctx context.Context, arg UpdateNarrativeSummaryParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateNarrativeSummary, arg.ID, arg.NarrativeSummary, arg.SummarizedThrough)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.NarrativeSummary,
		&i.DmNotes,
		&i.Status,
		&i.SummarizedThrough,
		&i.Party,
		&i.CharacterCreationComplete,
	)
	return i, err
}
