// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createCharacter = `-- name: CreateCharacter :one

INSERT INTO characters (name, class, user_id)
values ($1, $2, $3)
returning id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, status_effects, created_at, updated_at
`

type CreateCharacterParams struct {
	Name   string
	Class  string
	UserID uuid.UUID
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter, arg.Name, arg.Class, arg.UserID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.StatusEffects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec

delete from characters where id = $1 and user_id = $2
`

type DeleteCharacterParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, arg.ID, arg.UserID)
	return err
}

const getCharacterByID = `-- name: GetCharacterByID :one

select id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, status_effects, created_at, updated_at from characters where id = $1 AND user_id = $2
`

type GetCharacterByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCharacterByID(ctx context.Context, arg GetCharacterByIDParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacterByID, arg.ID, arg.UserID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.StatusEffects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterByUserID = `-- name: GetCharacterByUserID :many

select id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, status_effects, created_at, updated_at from characters where user_id = $1
`

func (q *Queries) GetCharacterByUserID(ctx context.Context, userID uuid.UUID) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Experience,
			&i.DrivingFate,
			&i.BindingFate,
			&i.Strength,
			&i.Dexterity,
			&i.Fortitude,
			&i.Willpower,
			&i.Alacrity,
			&i.Wisdom,
			&i.MaxHp,
			&i.CurrentHp,
			&i.MaxWp,
			&i.CurrentWp,
			&i.ActionPoints,
			&i.TalentPointsAvailable,
			&i.TalentsInvested,
			&i.Inventory,
			&i.StatusEffects,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacter = `-- name: UpdateCharacter :one

UPDATE characters
SET name = $1,
    class = $2,
    level = $3,
    strength = $4,
    dexterity = $5,
    fortitude = $6,
    willpower = $7,
    alacrity = $8,
    wisdom = $9,
    current_hp = $10,
    max_hp = $11,
    current_wp = $12,
    max_wp = $13,
    driving_fate = $14,
    binding_fate = $15,
    talents_invested = $16,
    talent_points_available = $17,
    inventory = $18,
    updated_at = NOW()
WHERE id = $19 AND user_id = $20
RETURNING id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, status_effects, created_at, updated_at
`

type UpdateCharacterParams struct {
	Name                  string
	Class                 string
	Level                 int32
	Strength              int32
	Dexterity             int32
	Fortitude             int32
	Willpower             int32
	Alacrity              int32
	Wisdom                int32
	CurrentHp             int32
	MaxHp                 int32
	CurrentWp             int32
	MaxWp                 int32
	DrivingFate           string
	BindingFate           string
	TalentsInvested       json.RawMessage
	TalentPointsAvailable int32
	Inventory             json.RawMessage
	ID                    uuid.UUID
	UserID                uuid.UUID
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacter,
		arg.Name,
		arg.Class,
		arg.Level,
		arg.Strength,
		arg.Dexterity,
		arg.Fortitude,
		arg.Willpower,
		arg.Alacrity,
		arg.Wisdom,
		arg.CurrentHp,
		arg.MaxHp,
		arg.CurrentWp,
		arg.MaxWp,
		arg.DrivingFate,
		arg.BindingFate,
		arg.TalentsInvested,
		arg.TalentPointsAvailable,
		arg.Inventory,
		arg.ID,
		arg.UserID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.StatusEffects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
