// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createCharacter = `-- name: CreateCharacter :one

INSERT INTO characters (name, class, user_id)
values ($1, $2, $3)
returning id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, created_at, updated_at, max_ap, overcap_ap, equipped_slots
`

type CreateCharacterParams struct {
	Name   string
	Class  string
	UserID uuid.UUID
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter, arg.Name, arg.Class, arg.UserID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAp,
		&i.OvercapAp,
		&i.EquippedSlots,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec

delete from characters where id = $1 and user_id = $2
`

type DeleteCharacterParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, arg.ID, arg.UserID)
	return err
}

const getCharacterByID = `-- name: GetCharacterByID :one

select id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, created_at, updated_at, max_ap, overcap_ap, equipped_slots from characters where id = $1
`

func (q *Queries) GetCharacterByID(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacterByID, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAp,
		&i.OvercapAp,
		&i.EquippedSlots,
	)
	return i, err
}

const getCharacterByUserID = `-- name: GetCharacterByUserID :many

select id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, created_at, updated_at, max_ap, overcap_ap, equipped_slots from characters where user_id = $1
`

func (q *Queries) GetCharacterByUserID(ctx context.Context, userID uuid.UUID) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Experience,
			&i.DrivingFate,
			&i.BindingFate,
			&i.Strength,
			&i.Dexterity,
			&i.Fortitude,
			&i.Willpower,
			&i.Alacrity,
			&i.Wisdom,
			&i.MaxHp,
			&i.CurrentHp,
			&i.MaxWp,
			&i.CurrentWp,
			&i.ActionPoints,
			&i.TalentPointsAvailable,
			&i.TalentsInvested,
			&i.Inventory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxAp,
			&i.OvercapAp,
			&i.EquippedSlots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacter = `-- name: UpdateCharacter :one

UPDATE characters
SET name = $1,
    race = $2,
    class = $3,
    level = $4,
    strength = $5,
    dexterity = $6,
    fortitude = $7,
    willpower = $8,
    alacrity = $9,
    wisdom = $10,
    current_hp = $11,
    max_hp = $12,
    current_wp = $13,
    max_wp = $14,
    driving_fate = $15,
    binding_fate = $16,
    talents_invested = $17,
    talent_points_available = $18,
    inventory = $19,
    updated_at = NOW(),
    max_ap = $20,
    overcap_ap = $21,
    action_points = $22,
    equipped_slots = $23

WHERE id = $24
RETURNING id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, created_at, updated_at, max_ap, overcap_ap, equipped_slots
`

type UpdateCharacterParams struct {
	Name                  string
	Race                  string
	Class                 string
	Level                 int32
	Strength              int32
	Dexterity             int32
	Fortitude             int32
	Willpower             int32
	Alacrity              int32
	Wisdom                int32
	CurrentHp             int32
	MaxHp                 int32
	CurrentWp             int32
	MaxWp                 int32
	DrivingFate           string
	BindingFate           string
	TalentsInvested       json.RawMessage
	TalentPointsAvailable int32
	Inventory             json.RawMessage
	MaxAp                 int32
	OvercapAp             int32
	ActionPoints          int32
	EquippedSlots         pqtype.NullRawMessage
	ID                    uuid.UUID
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacter,
		arg.Name,
		arg.Race,
		arg.Class,
		arg.Level,
		arg.Strength,
		arg.Dexterity,
		arg.Fortitude,
		arg.Willpower,
		arg.Alacrity,
		arg.Wisdom,
		arg.CurrentHp,
		arg.MaxHp,
		arg.CurrentWp,
		arg.MaxWp,
		arg.DrivingFate,
		arg.BindingFate,
		arg.TalentsInvested,
		arg.TalentPointsAvailable,
		arg.Inventory,
		arg.MaxAp,
		arg.OvercapAp,
		arg.ActionPoints,
		arg.EquippedSlots,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAp,
		&i.OvercapAp,
		&i.EquippedSlots,
	)
	return i, err
}

const updateCharacterEquippedSlots = `-- name: UpdateCharacterEquippedSlots :one
UPDATE characters
SET equipped_slots = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, created_at, updated_at, max_ap, overcap_ap, equipped_slots
`

type UpdateCharacterEquippedSlotsParams struct {
	ID            uuid.UUID
	EquippedSlots pqtype.NullRawMessage
}

func (q *Queries) UpdateCharacterEquippedSlots(ctx context.Context, arg UpdateCharacterEquippedSlotsParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterEquippedSlots, arg.ID, arg.EquippedSlots)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAp,
		&i.OvercapAp,
		&i.EquippedSlots,
	)
	return i, err
}

const updateCharacterHP = `-- name: UpdateCharacterHP :exec
UPDATE characters SET current_hp = $2 WHERE id = $1
`

type UpdateCharacterHPParams struct {
	ID        uuid.UUID
	CurrentHp int32
}

func (q *Queries) UpdateCharacterHP(ctx context.Context, arg UpdateCharacterHPParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterHP, arg.ID, arg.CurrentHp)
	return err
}

const updateCharacterInventory = `-- name: UpdateCharacterInventory :one
UPDATE characters
SET inventory = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, created_at, updated_at, max_ap, overcap_ap, equipped_slots
`

type UpdateCharacterInventoryParams struct {
	ID        uuid.UUID
	Inventory json.RawMessage
}

func (q *Queries) UpdateCharacterInventory(ctx context.Context, arg UpdateCharacterInventoryParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterInventory, arg.ID, arg.Inventory)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAp,
		&i.OvercapAp,
		&i.EquippedSlots,
	)
	return i, err
}

const updateCharacterLevel = `-- name: UpdateCharacterLevel :one
UPDATE characters
SET level = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, created_at, updated_at, max_ap, overcap_ap, equipped_slots
`

type UpdateCharacterLevelParams struct {
	ID    uuid.UUID
	Level int32
}

func (q *Queries) UpdateCharacterLevel(ctx context.Context, arg UpdateCharacterLevelParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterLevel, arg.ID, arg.Level)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAp,
		&i.OvercapAp,
		&i.EquippedSlots,
	)
	return i, err
}

const updateCharacterWP = `-- name: UpdateCharacterWP :exec
UPDATE characters SET current_wp = $2 WHERE id = $1
`

type UpdateCharacterWPParams struct {
	ID        uuid.UUID
	CurrentWp int32
}

func (q *Queries) UpdateCharacterWP(ctx context.Context, arg UpdateCharacterWPParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterWP, arg.ID, arg.CurrentWp)
	return err
}

const updateCharacterXP = `-- name: UpdateCharacterXP :one
UPDATE characters
SET experience = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, race, class, level, experience, driving_fate, binding_fate, strength, dexterity, fortitude, willpower, alacrity, wisdom, max_hp, current_hp, max_wp, current_wp, action_points, talent_points_available, talents_invested, inventory, created_at, updated_at, max_ap, overcap_ap, equipped_slots
`

type UpdateCharacterXPParams struct {
	ID         uuid.UUID
	Experience int32
}

func (q *Queries) UpdateCharacterXP(ctx context.Context, arg UpdateCharacterXPParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterXP, arg.ID, arg.Experience)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Experience,
		&i.DrivingFate,
		&i.BindingFate,
		&i.Strength,
		&i.Dexterity,
		&i.Fortitude,
		&i.Willpower,
		&i.Alacrity,
		&i.Wisdom,
		&i.MaxHp,
		&i.CurrentHp,
		&i.MaxWp,
		&i.CurrentWp,
		&i.ActionPoints,
		&i.TalentPointsAvailable,
		&i.TalentsInvested,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAp,
		&i.OvercapAp,
		&i.EquippedSlots,
	)
	return i, err
}

const validateCharacterOwnership = `-- name: ValidateCharacterOwnership :one
SELECT id FROM characters WHERE id = $1 AND user_id = $2
`

type ValidateCharacterOwnershipParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ValidateCharacterOwnership(ctx context.Context, arg ValidateCharacterOwnershipParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, validateCharacterOwnership, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
