// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: combat.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createCombatSession = `-- name: CreateCombatSession :one
INSERT INTO combat_sessions (campaign_id, current_turn, turn_order, combatants)
VALUES ($1, $2, $3, $4)
RETURNING id, campaign_id, status, round, current_turn, turn_order, combatants, created_at, updated_at
`

type CreateCombatSessionParams struct {
	CampaignID  uuid.NullUUID
	CurrentTurn uuid.UUID
	TurnOrder   json.RawMessage
	Combatants  json.RawMessage
}

func (q *Queries) CreateCombatSession(ctx context.Context, arg CreateCombatSessionParams) (CombatSession, error) {
	row := q.db.QueryRowContext(ctx, createCombatSession,
		arg.CampaignID,
		arg.CurrentTurn,
		arg.TurnOrder,
		arg.Combatants,
	)
	var i CombatSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.Round,
		&i.CurrentTurn,
		&i.TurnOrder,
		&i.Combatants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endCombatSession = `-- name: EndCombatSession :one
UPDATE combat_sessions
SET status = 'ended',
    updated_at = NOW()
WHERE id = $1
RETURNING id, campaign_id, status, round, current_turn, turn_order, combatants, created_at, updated_at
`

func (q *Queries) EndCombatSession(ctx context.Context, id uuid.UUID) (CombatSession, error) {
	row := q.db.QueryRowContext(ctx, endCombatSession, id)
	var i CombatSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.Round,
		&i.CurrentTurn,
		&i.TurnOrder,
		&i.Combatants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCombatBySession = `-- name: GetActiveCombatBySession :one
SELECT id, campaign_id, status, round, current_turn, turn_order, combatants, created_at, updated_at FROM combat_sessions
WHERE id = $1 AND status = 'active'
`

func (q *Queries) GetActiveCombatBySession(ctx context.Context, id uuid.UUID) (CombatSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveCombatBySession, id)
	var i CombatSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.Round,
		&i.CurrentTurn,
		&i.TurnOrder,
		&i.Combatants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCombatSession = `-- name: GetCombatSession :one
SELECT id, campaign_id, status, round, current_turn, turn_order, combatants, created_at, updated_at FROM combat_sessions
WHERE id = $1
`

func (q *Queries) GetCombatSession(ctx context.Context, id uuid.UUID) (CombatSession, error) {
	row := q.db.QueryRowContext(ctx, getCombatSession, id)
	var i CombatSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.Round,
		&i.CurrentTurn,
		&i.TurnOrder,
		&i.Combatants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCombatState = `-- name: UpdateCombatState :one
UPDATE combat_sessions
SET current_turn = $2,
    turn_order = $3,
    combatants = $4,
    round = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, campaign_id, status, round, current_turn, turn_order, combatants, created_at, updated_at
`

type UpdateCombatStateParams struct {
	ID          uuid.UUID
	CurrentTurn uuid.UUID
	TurnOrder   json.RawMessage
	Combatants  json.RawMessage
	Round       int32
}

func (q *Queries) UpdateCombatState(ctx context.Context, arg UpdateCombatStateParams) (CombatSession, error) {
	row := q.db.QueryRowContext(ctx, updateCombatState,
		arg.ID,
		arg.CurrentTurn,
		arg.TurnOrder,
		arg.Combatants,
		arg.Round,
	)
	var i CombatSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.Round,
		&i.CurrentTurn,
		&i.TurnOrder,
		&i.Combatants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
