// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countMessagesAfterSequence = `-- name: CountMessagesAfterSequence :one
SELECT COUNT(*) FROM messages
WHERE campaign_id = $1
AND sequence > $2
`

type CountMessagesAfterSequenceParams struct {
	CampaignID uuid.UUID
	Sequence   int32
}

func (q *Queries) CountMessagesAfterSequence(ctx context.Context, arg CountMessagesAfterSequenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessagesAfterSequence, arg.CampaignID, arg.Sequence)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessagesByCampaign = `-- name: DeleteMessagesByCampaign :exec
DELETE FROM messages
WHERE campaign_id = $1
`

func (q *Queries) DeleteMessagesByCampaign(ctx context.Context, campaignID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesByCampaign, campaignID)
	return err
}

const getMessageCount = `-- name: GetMessageCount :one
SELECT COUNT(*) FROM messages
WHERE campaign_id = $1
`

func (q *Queries) GetMessageCount(ctx context.Context, campaignID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageCount, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessagesAfterSequence = `-- name: GetMessagesAfterSequence :many
SELECT id, campaign_id, role, content, tool_calls, tool_call_id, sequence, created_at FROM messages
WHERE campaign_id = $1
AND sequence > $2
ORDER BY sequence ASC
`

type GetMessagesAfterSequenceParams struct {
	CampaignID uuid.UUID
	Sequence   int32
}

func (q *Queries) GetMessagesAfterSequence(ctx context.Context, arg GetMessagesAfterSequenceParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesAfterSequence, arg.CampaignID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.Sequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByCampaign = `-- name: GetMessagesByCampaign :many
SELECT id, campaign_id, role, content, tool_calls, tool_call_id, sequence, created_at FROM messages
WHERE campaign_id = $1
ORDER BY sequence ASC
`

func (q *Queries) GetMessagesByCampaign(ctx context.Context, campaignID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.Sequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextSequence = `-- name: GetNextSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1 AS next_sequence
FROM messages
WHERE campaign_id = $1
`

func (q *Queries) GetNextSequence(ctx context.Context, campaignID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextSequence, campaignID)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const getRecentMessages = `-- name: GetRecentMessages :many
SELECT id, campaign_id, role, content, tool_calls, tool_call_id, sequence, created_at FROM messages
WHERE campaign_id = $1
ORDER BY sequence DESC
LIMIT $2
`

type GetRecentMessagesParams struct {
	CampaignID uuid.UUID
	Limit      int32
}

func (q *Queries) GetRecentMessages(ctx context.Context, arg GetRecentMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessages, arg.CampaignID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.Sequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (campaign_id, role, content, tool_calls, tool_call_id, sequence)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, role, content, tool_calls, tool_call_id, sequence, created_at
`

type InsertMessageParams struct {
	CampaignID uuid.UUID
	Role       string
	Content    string
	ToolCalls  json.RawMessage
	ToolCallID string
	Sequence   int32
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.CampaignID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
		arg.Sequence,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.Sequence,
		&i.CreatedAt,
	)
	return i, err
}
