// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type CombatStatus string

const (
	CombatStatusActive CombatStatus = "active"
	CombatStatusEnded  CombatStatus = "ended"
)

func (e *CombatStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CombatStatus(s)
	case string:
		*e = CombatStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CombatStatus: %T", src)
	}
	return nil
}

type NullCombatStatus struct {
	CombatStatus CombatStatus
	Valid        bool // Valid is true if CombatStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCombatStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CombatStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CombatStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCombatStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CombatStatus), nil
}

type Campaign struct {
	ID                uuid.UUID
	Name              string
	OwnerID           uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Theme             string
	NarrativeSummary  string
	DmNotes           string
	Status            string
	SummarizedThrough int32
	Party             json.RawMessage
}

type Character struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	Name                  string
	Race                  string
	Class                 string
	Level                 int32
	Experience            int32
	DrivingFate           string
	BindingFate           string
	Strength              int32
	Dexterity             int32
	Fortitude             int32
	Willpower             int32
	Alacrity              int32
	Wisdom                int32
	MaxHp                 int32
	CurrentHp             int32
	MaxWp                 int32
	CurrentWp             int32
	ActionPoints          int32
	TalentPointsAvailable int32
	TalentsInvested       json.RawMessage
	Inventory             json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
	MaxAp                 int32
	OvercapAp             int32
	EquippedSlots         pqtype.NullRawMessage
}

type CombatSession struct {
	ID          uuid.UUID
	CampaignID  uuid.NullUUID
	Status      CombatStatus
	Round       int32
	CurrentTurn uuid.UUID
	TurnOrder   json.RawMessage
	Combatants  json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Message struct {
	ID         uuid.UUID
	CampaignID uuid.UUID
	Role       string
	Content    string
	ToolCalls  json.RawMessage
	ToolCallID string
	Sequence   int32
	CreatedAt  time.Time
}

type StatusEffect struct {
	ID          uuid.UUID
	CharacterID uuid.UUID
	Effect      string
	Duration    int32
	IsActive    bool
	Persists    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Instruction string
}

type User struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
	CreatedAt      time.Time
	ModifiedAt     time.Time
}
