// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_effects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addStatusEffect = `-- name: AddStatusEffect :one

INSERT INTO status_effects (character_id, effect, duration, persists, instruction)
values ($1, $2, $3, $4, $5)
returning id, character_id, effect, duration, is_active, persists, created_at, updated_at, instruction
`

type AddStatusEffectParams struct {
	CharacterID uuid.UUID
	Effect      string
	Duration    int32
	Persists    bool
	Instruction string
}

func (q *Queries) AddStatusEffect(ctx context.Context, arg AddStatusEffectParams) (StatusEffect, error) {
	row := q.db.QueryRowContext(ctx, addStatusEffect,
		arg.CharacterID,
		arg.Effect,
		arg.Duration,
		arg.Persists,
		arg.Instruction,
	)
	var i StatusEffect
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Effect,
		&i.Duration,
		&i.IsActive,
		&i.Persists,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Instruction,
	)
	return i, err
}

const getStatusEffectsByID = `-- name: GetStatusEffectsByID :many

SELECT id, character_id, effect, duration, is_active, persists, created_at, updated_at, instruction FROM status_effects WHERE character_id = $1 and is_active = TRUE
`

func (q *Queries) GetStatusEffectsByID(ctx context.Context, characterID uuid.UUID) ([]StatusEffect, error) {
	rows, err := q.db.QueryContext(ctx, getStatusEffectsByID, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusEffect
	for rows.Next() {
		var i StatusEffect
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Effect,
			&i.Duration,
			&i.IsActive,
			&i.Persists,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Instruction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeInactiveEffects = `-- name: PurgeInactiveEffects :exec

DELETE FROM status_effects
WHERE character_id = $1 AND is_active = FALSE
`

func (q *Queries) PurgeInactiveEffects(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, purgeInactiveEffects, characterID)
	return err
}

const purgeNonPersistingEffects = `-- name: PurgeNonPersistingEffects :exec

DELETE FROM status_effects
WHERE character_id = $1 AND persists = FALSE
`

func (q *Queries) PurgeNonPersistingEffects(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, purgeNonPersistingEffects, characterID)
	return err
}

const updateStatusDuration = `-- name: UpdateStatusDuration :one

UPDATE status_effects
SET duration = $3,
    updated_at = NOW(),
    is_active = $4
where id = $1 and character_id = $2
returning id, character_id, effect, duration, is_active, persists, created_at, updated_at, instruction
`

type UpdateStatusDurationParams struct {
	ID          uuid.UUID
	CharacterID uuid.UUID
	Duration    int32
	IsActive    bool
}

func (q *Queries) UpdateStatusDuration(ctx context.Context, arg UpdateStatusDurationParams) (StatusEffect, error) {
	row := q.db.QueryRowContext(ctx, updateStatusDuration,
		arg.ID,
		arg.CharacterID,
		arg.Duration,
		arg.IsActive,
	)
	var i StatusEffect
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Effect,
		&i.Duration,
		&i.IsActive,
		&i.Persists,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Instruction,
	)
	return i, err
}
